"""Create a compact GVEC MHD equilibrium, then use it as a Struphy magnetic geometry.

GVEC first minimizes a circular-tokamak MHD equilibrium defined entirely by
a Python parameter dictionary. Its newly written final state is passed directly to Struphy's `GVECequilibrium`,
which supplies both the curved `GVECunit` mapping and the equilibrium magnetic
field to a short shear-Alfvén simulation. The figures expose the resulting
three-dimensional flux geometry, a poloidal cut and the radial equilibrium
profiles, as well as the perturbation energies from the Struphy run.

Requires the optional physics dependencies (`pip install -e ".[phys]"`) and
compiled Struphy kernels (`struphy compile`).
"""

from pathlib import Path

import h5py
import numpy as np
import plotly.graph_objects as go

from struphy import (
    DerhamOptions,
    EnvironmentOptions,
    Simulation,
    Time,
    domains,
    equils,
    grids,
    perturbations,
)
from struphy.models import ShearAlfven

# Keep both the GVEC solve and the following FEEC simulation deliberately
# small. The complete equilibrium input is defined below, so the example has
# no external parameter or state-file dependency.
mapping_elements = (4, 8, 4)
mapping_degree = (2, 2, 2)
velocity_amplitude = 1.0e-4


def gvec_parameters() -> dict:
    """A complete axisymmetric circular-tokamak equilibrium, defined through pyGVEC's API."""
    return {
        "ProjectName": "struphy_gallery_gvec",
        "whichInitEquilibrium": 0,
        "init_LA": True,
        "iota": {"type": "polynomial", "scale": 1.0, "coefs": (0.625, 0.523)},
        "pres": {"type": "polynomial", "scale": 1.0, "coefs": (0.02, -0.0136878012275)},
        "PsiEdge": 1.0,
        # Circular magnetic axis at R=5 and an elliptical last closed flux
        # surface with radial and vertical half-widths 0.9 and 1.1.
        "X1_b_cos": {(0, 0): 5.0, (1, 0): 0.9},
        "X2_b_sin": {(1, 0): 1.1},
        "X1_a_cos": {(0, 0): 5.0},
        "sgrid": {"nElems": 5, "grid_type": 0},
        "degGP": 8,
        "X1X2_deg": 5,
        "LA_deg": 5,
        "X1_mn_max": (2, 0),
        "X2_mn_max": (2, 0),
        "LA_mn_max": (2, 0),
        "X1_sin_cos": "_cos_",
        "X2_sin_cos": "_sin_",
        "LA_sin_cos": "_sin_",
        "nfp": 1,
        "start_dt": 0.5,
        "PrecondType": 1,
        "MinimizerType": 10,
        "maxiter": 200,
        "totaliter": 200,
        "minimize_tol": 1.0e-4,
    }


def create_gvec_equilibrium(workdir: Path) -> tuple[equils.GVECequilibrium, int, float]:
    """Run GVEC from our Python parameters and expose its new final state to Struphy."""
    import gvec

    # pyGVEC writes our new parameter and state files into `workdir`. This
    # compact case normally converges in roughly one hundred iterations.
    run = gvec.run(
        gvec_parameters(), runpath=workdir, quiet=True, redirect_gvec_stdout=True
    )
    equilibrium = equils.GVECequilibrium(
        rel_path=False,
        param_file=str(run.state.parameterfile),
        dat_file=str(run.state.statefile),
        use_nfp=False,
        num_elements=mapping_elements,
        degree=mapping_degree,
    )
    return equilibrium, int(run.GVEC_iter_used), float(run.max_force)


def make_simulation(equilibrium, folder: str, domain=None, **extra) -> Simulation:
    model = ShearAlfven()
    # A physical transverse mode. Struphy maps and projects it onto GVEC's
    # physical torus before advancing it with the numerical B0 field.
    model.mhd.velocity.add_perturbation(
        perturbations.ModesSin(
            ns=(1,), amps=(velocity_amplitude,), comp=0, given_in_basis="physical"
        )
    )
    return Simulation(
        model=model,
        env=EnvironmentOptions(out_folders="struphy_gallery_runs", sim_folder=folder),
        time_opts=Time(dt=0.01, Tend=0.10),
        domain=domain or equilibrium.numerical_domain,
        equil=equilibrium,
        grid=grids.TensorProductGrid(num_elements=mapping_elements),
        derham_opts=DerhamOptions(degree=mapping_degree),
        **extra,
    )


# Metadata generation imports this script without executing GVEC. The cheap
# placeholder below is never run; `metadata_overrides` records the runtime
# geometry, while the executable block replaces it with our generated state.
simulation_details = {
    "name": "GVEC equilibrium in a Struphy simulation",
    "description": (
        "GVEC creates a circular-tokamak MHD equilibrium, then Struphy loads its final state as the "
        "magnetic field and curved geometry for a short shear-Alfvén simulation."
    ),
}
sim = make_simulation(
    equils.HomogenSlab(B0z=1.0),
    "gvec_equilibrium_metadata",
    domain=domains.Cuboid(),
    **simulation_details,
)
metadata_overrides = {"domain": "GVECunit (generated by pyGVEC)"}


if __name__ == "__main__":
    from plotly.subplots import make_subplots

    from _gallery import (
        export_profiling,
        merge_metadata,
        save_extra_figure,
        save_figure,
    )

    gvec_directory = Path("struphy_gallery_runs/gvec_equilibrium_source")
    gvec_directory.parent.mkdir(parents=True, exist_ok=True)
    equilibrium, gvec_iterations, gvec_force = create_gvec_equilibrium(gvec_directory)
    run = make_simulation(
        equilibrium, "gvec_equilibrium", name=sim.name, description=sim.description
    )
    run.run(profiling_activated=True)

    # Scalar diagnostics are rank-independent and live in the first HDF5 file.
    # Reading them directly also keeps this example focused on the GVEC handoff.
    data_file = Path(run.env.path_out) / "data/data_proc0.hdf5"
    with h5py.File(data_file) as data:
        time = np.asarray(data["time/value"])
        kinetic = np.asarray(data["scalar/en_U"])
        magnetic = np.asarray(data["scalar/en_B"])
        total = np.asarray(data["scalar/en_tot"])
    scale = float(total[0])
    relative_drift = float(np.max(np.abs(total / scale - 1.0)))
    if not np.isfinite(relative_drift):
        raise RuntimeError("Non-finite energy diagnostic in the GVEC-backed simulation")
    print(
        f"GVEC converged in {gvec_iterations} iterations to |force| = {gvec_force:.2e}; "
        f"field periods: {equilibrium.state.nfp}; perturbation-energy drift: {relative_drift:.2e}"
    )

    # A cutaway torus makes the nested GVEC flux surfaces visible instead of
    # hiding all of them behind the last closed surface. Color is |B|, so the
    # familiar stronger inboard / weaker outboard tokamak field is visible too.
    surface_radii = np.array((0.2, 0.4, 0.6, 0.8, 1.0))
    toroidal_angles = np.linspace(0.05 * np.pi, 1.95 * np.pi, 97)
    surface_data = equilibrium.state.evaluate(
        "pos",
        "mod_B",
        rho=surface_radii,
        theta=49,
        zeta=toroidal_angles,
    )
    positions = np.asarray(surface_data["pos"])
    field_strength = np.asarray(surface_data["mod_B"])
    field_min = float(np.nanmin(field_strength))
    field_max = float(np.nanmax(field_strength))

    figure = go.Figure()
    for index, radius in enumerate(surface_radii):
        # Trim progressively more toroidal sections from the larger shells.
        # The staggered cut exposes every nested surface in the open wedge.
        trim = 3 * index
        toroidal_slice = slice(trim, len(toroidal_angles) - trim)
        figure.add_trace(
            go.Surface(
                x=positions[0, index, :, toroidal_slice],
                y=positions[1, index, :, toroidal_slice],
                z=positions[2, index, :, toroidal_slice],
                surfacecolor=field_strength[index, :, toroidal_slice],
                cmin=field_min,
                cmax=field_max,
                colorscale="Viridis",
                opacity=0.82 if radius < 1.0 else 0.68,
                showscale=index == len(surface_radii) - 1,
                colorbar={"title": "|B|", "len": 0.72},
                name=f"ρ = {radius:.1f}",
                hovertemplate=(
                    f"ρ = {radius:.1f}<br>R = %{{customdata:.3f}}<br>"
                    "Z = %{z:.3f}<br>|B| = %{surfacecolor:.3f}<extra></extra>"
                ),
                customdata=np.sqrt(
                    positions[0, index, :, toroidal_slice] ** 2
                    + positions[1, index, :, toroidal_slice] ** 2
                ),
            )
        )
    figure.update_layout(
        title="GVEC equilibrium: nested magnetic flux surfaces",
        template="plotly_white",
        scene={
            "xaxis_title": "x",
            "yaxis_title": "y",
            "zaxis_title": "z",
            "aspectmode": "data",
            "camera": {"eye": {"x": 1.45, "y": 1.45, "z": 0.85}},
        },
        margin={"l": 10, "r": 30, "t": 75, "b": 10},
    )
    save_figure(figure, "gvec-equilibrium", height=760)

    # A poloidal slice reveals the nesting more quantitatively; the adjacent
    # radial profiles come from the very same state file used by Struphy.
    cut_radii = np.linspace(0.1, 1.0, 10)
    cut_data = equilibrium.state.evaluate(
        "pos", rho=cut_radii, theta=181, zeta=np.array((0.0,))
    )
    cut_positions = np.asarray(cut_data["pos"])
    profile_radii = np.linspace(0.0, 1.0, 101)
    profile_data = equilibrium.state.evaluate(
        "iota", "p", rho=profile_radii, theta=0, zeta=0
    )

    profiles = make_subplots(
        rows=1,
        cols=2,
        specs=[[{}, {"secondary_y": True}]],
        subplot_titles=(
            "Poloidal flux surfaces (ζ = 0)",
            "Radial equilibrium profiles",
        ),
        horizontal_spacing=0.14,
    )
    for index, radius in enumerate(cut_radii):
        x = cut_positions[0, index, :, 0]
        y = cut_positions[1, index, :, 0]
        z = cut_positions[2, index, :, 0]
        radial_position = np.sqrt(x**2 + y**2)
        profiles.add_scatter(
            x=np.append(radial_position, radial_position[0]),
            y=np.append(z, z[0]),
            mode="lines",
            line={"color": "#168aad", "width": 1.5 + 1.2 * radius},
            opacity=0.35 + 0.65 * radius,
            name=f"ρ = {radius:.1f}",
            legendgroup="surfaces",
            showlegend=index in (0, len(cut_radii) - 1),
            row=1,
            col=1,
        )
    profiles.add_scatter(
        x=profile_radii,
        y=np.asarray(profile_data["p"]),
        mode="lines",
        name="pressure p",
        line={"color": "#d62828", "width": 3},
        row=1,
        col=2,
        secondary_y=False,
    )
    profiles.add_scatter(
        x=profile_radii,
        y=np.asarray(profile_data["iota"]),
        mode="lines",
        name="rotational transform ι",
        line={"color": "#f4a261", "width": 3},
        row=1,
        col=2,
        secondary_y=True,
    )
    profiles.update_xaxes(title_text="R", scaleanchor="y", scaleratio=1, row=1, col=1)
    profiles.update_yaxes(title_text="Z", row=1, col=1)
    profiles.update_xaxes(title_text="normalized flux radius ρ", row=1, col=2)
    profiles.update_yaxes(title_text="pressure p", row=1, col=2, secondary_y=False)
    profiles.update_yaxes(
        title_text="rotational transform ι", row=1, col=2, secondary_y=True
    )
    profiles.update_layout(
        title="GVEC flux geometry and equilibrium profiles",
        template="plotly_white",
        legend={"orientation": "h", "y": -0.2},
        margin={"l": 70, "r": 70, "t": 90, "b": 100},
    )
    figures = [
        save_extra_figure(
            profiles,
            "gvec-equilibrium",
            "flux-surfaces",
            alt="Nested GVEC flux surfaces in a poloidal cut beside pressure and rotational-transform profiles",
            caption=(
                "A poloidal cut through the nested magnetic surfaces generated by GVEC. "
                "The pressure and rotational transform on the right are evaluated directly "
                "from the newly generated equilibrium state."
            ),
        )
    ]

    energy_figure = go.Figure()
    energy_figure.add_scatter(
        x=time,
        y=kinetic / scale,
        mode="lines",
        name="kinetic",
        line={"color": "#168aad", "width": 2.5},
    )
    energy_figure.add_scatter(
        x=time,
        y=magnetic / scale,
        mode="lines",
        name="magnetic",
        line={"color": "#d62828", "width": 2.5},
    )
    energy_figure.add_scatter(
        x=time,
        y=total / scale,
        mode="lines",
        name="total",
        line={"color": "#264653", "width": 2.5},
    )
    energy_figure.update_layout(
        title="Shear-Alfvén perturbation on the GVEC equilibrium",
        xaxis_title="t [a.u.]",
        yaxis_title="energy / initial perturbation energy",
        template="plotly_white",
        autosize=True,
        legend={"orientation": "h", "y": -0.18},
        margin={"l": 75, "r": 30, "t": 80, "b": 100},
    )
    figures.append(
        save_extra_figure(
            energy_figure,
            "gvec-equilibrium",
            "energies",
            alt="Kinetic, magnetic and total perturbation energies in the GVEC-backed Struphy run",
            caption=(
                "Energy exchange during the short shear-Alfvén simulation that uses the generated "
                "GVEC state for both its curved domain and equilibrium magnetic field."
            ),
        )
    )
    merge_metadata(
        "gvec-equilibrium",
        gvecIterations=gvec_iterations,
        gvecFinalForce=gvec_force,
        gvecFieldPeriods=int(equilibrium.state.nfp),
        relativeEnergyDrift=relative_drift,
        figures=figures,
        **export_profiling(run, "gvec-equilibrium"),
    )
