"""Create a compact G-Vec MHD equilibrium, then use it as a Struphy magnetic geometry.

G-Vec first minimizes a circular-tokamak MHD equilibrium defined entirely by
a Python parameter dictionary. Its newly written final state is passed directly to Struphy's `GVECequilibrium`,
which supplies both the curved `GVECunit` mapping and the equilibrium magnetic
field to a short shear-Alfvén simulation.  The plotted perturbation energies
show that the run uses this numerical equilibrium rather than an analytic
slab field.

Requires the optional physics dependencies (`pip install -e ".[phys]"`) and
compiled Struphy kernels (`struphy compile`).
"""

from pathlib import Path

import h5py
import numpy as np
import plotly.graph_objects as go

from struphy import DerhamOptions, EnvironmentOptions, Simulation, Time, domains, equils, grids, perturbations
from struphy.models import ShearAlfven

# Keep both the G-Vec solve and the following FEEC simulation deliberately
# small. The complete equilibrium input is defined below, so the example has
# no external parameter or state-file dependency.
mapping_elements = (4, 8, 4)
mapping_degree = (2, 2, 2)
velocity_amplitude = 1.0e-4


def gvec_parameters() -> dict:
    """A complete axisymmetric circular-tokamak equilibrium, defined through pyGVEC's API."""
    return {
        "ProjectName": "struphy_gallery_gvec",
        "whichInitEquilibrium": 0,
        "init_LA": True,
        "iota": {"type": "polynomial", "scale": 1.0, "coefs": (0.625, 0.523)},
        "pres": {"type": "polynomial", "scale": 1.0, "coefs": (0.02, -0.0136878012275)},
        "PsiEdge": 1.0,
        # Circular magnetic axis at R=5 and an elliptical last closed flux
        # surface with radial and vertical half-widths 0.9 and 1.1.
        "X1_b_cos": {(0, 0): 5.0, (1, 0): 0.9},
        "X2_b_sin": {(1, 0): 1.1},
        "X1_a_cos": {(0, 0): 5.0},
        "sgrid": {"nElems": 5, "grid_type": 0},
        "degGP": 8,
        "X1X2_deg": 5,
        "LA_deg": 5,
        "X1_mn_max": (2, 0),
        "X2_mn_max": (2, 0),
        "LA_mn_max": (2, 0),
        "X1_sin_cos": "_cos_",
        "X2_sin_cos": "_sin_",
        "LA_sin_cos": "_sin_",
        "nfp": 1,
        "start_dt": 0.5,
        "PrecondType": 1,
        "MinimizerType": 10,
        "maxiter": 200,
        "totaliter": 200,
        "minimize_tol": 1.0e-4,
    }


def create_gvec_equilibrium(workdir: Path) -> tuple[equils.GVECequilibrium, int, float]:
    """Run G-Vec from our Python parameters and expose its new final state to Struphy."""
    import gvec
    # pyGVEC writes our new parameter and state files into `workdir`. This
    # compact case normally converges in roughly one hundred iterations.
    run = gvec.run(gvec_parameters(), runpath=workdir, quiet=True, redirect_gvec_stdout=True)
    equilibrium = equils.GVECequilibrium(
        rel_path=False,
        param_file=str(run.state.parameterfile),
        dat_file=str(run.state.statefile),
        use_nfp=False,
        num_elements=mapping_elements,
        degree=mapping_degree,
    )
    return equilibrium, int(run.GVEC_iter_used), float(run.max_force)


def make_simulation(equilibrium, folder: str, domain=None, **extra) -> Simulation:
    model = ShearAlfven()
    # A physical transverse mode. Struphy maps and projects it onto G-Vec's
    # physical torus before advancing it with the numerical B0 field.
    model.mhd.velocity.add_perturbation(
        perturbations.ModesSin(ns=(1,), amps=(velocity_amplitude,), comp=0, given_in_basis="physical")
    )
    return Simulation(
        model=model,
        env=EnvironmentOptions(out_folders="struphy_gallery_runs", sim_folder=folder),
        time_opts=Time(dt=0.01, Tend=0.10),
        domain=domain or equilibrium.numerical_domain,
        equil=equilibrium,
        grid=grids.TensorProductGrid(num_elements=mapping_elements),
        derham_opts=DerhamOptions(degree=mapping_degree),
        **extra,
    )


# Metadata generation imports this script without executing G-Vec. The cheap
# placeholder below is never run; `metadata_overrides` records the runtime
# geometry, while the executable block replaces it with our generated state.
simulation_details = {
    "name": "G-Vec equilibrium in a Struphy simulation",
    "description": (
        "G-Vec creates a circular-tokamak MHD equilibrium, then Struphy loads its final state as the "
        "magnetic field and curved geometry for a short shear-Alfvén simulation."
    ),
}
sim = make_simulation(
    equils.HomogenSlab(B0z=1.0), "gvec_equilibrium_metadata",
    domain=domains.Cuboid(), **simulation_details,
)
metadata_overrides = {"domain": "GVECunit (generated by pyGVEC)"}


if __name__ == "__main__":
    from _gallery import export_profiling, merge_metadata, save_figure

    gvec_directory = Path("struphy_gallery_runs/gvec_equilibrium_source")
    gvec_directory.parent.mkdir(parents=True, exist_ok=True)
    equilibrium, gvec_iterations, gvec_force = create_gvec_equilibrium(gvec_directory)
    run = make_simulation(equilibrium, "gvec_equilibrium", name=sim.name, description=sim.description)
    run.run(profiling_activated=True)

    # Scalar diagnostics are rank-independent and live in the first HDF5 file.
    # Reading them directly also keeps this example focused on the G-Vec handoff.
    data_file = Path(run.env.path_out) / "data/data_proc0.hdf5"
    with h5py.File(data_file) as data:
        time = np.asarray(data["time/value"])
        kinetic = np.asarray(data["scalar/en_U"])
        magnetic = np.asarray(data["scalar/en_B"])
        total = np.asarray(data["scalar/en_tot"])
    scale = float(total[0])
    relative_drift = float(np.max(np.abs(total / scale - 1.0)))
    if not np.isfinite(relative_drift):
        raise RuntimeError("Non-finite energy diagnostic in the G-Vec-backed simulation")
    print(
        f"G-Vec converged in {gvec_iterations} iterations to |force| = {gvec_force:.2e}; "
        f"field periods: {equilibrium.state.nfp}; perturbation-energy drift: {relative_drift:.2e}"
    )

    figure = go.Figure()
    figure.add_scatter(x=time, y=kinetic / scale, mode="lines", name="kinetic", line={"color": "#168aad", "width": 2.5})
    figure.add_scatter(x=time, y=magnetic / scale, mode="lines", name="magnetic", line={"color": "#d62828", "width": 2.5})
    figure.add_scatter(x=time, y=total / scale, mode="lines", name="total", line={"color": "#264653", "width": 2.5})
    figure.update_layout(
        title="Shear-Alfvén perturbation on a G-Vec circular-tokamak equilibrium",
        xaxis_title="t [a.u.]", yaxis_title="energy / initial perturbation energy",
        template="plotly_white", autosize=True, legend={"orientation": "h", "y": -0.18},
        margin={"l": 75, "r": 30, "t": 80, "b": 100},
    )
    save_figure(figure, "gvec-equilibrium")
    merge_metadata(
        "gvec-equilibrium", gvecIterations=gvec_iterations, gvecFinalForce=gvec_force,
        gvecFieldPeriods=int(equilibrium.state.nfp), relativeEnergyDrift=relative_drift,
        **export_profiling(run, "gvec-equilibrium"),
    )
