name: Test site build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: test-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-site.yml
    permissions:
      contents: read
      packages: read
